version: 2.1

aliases:
  - &runner
    executor:
      name: node/default
      tag: << parameters.node-version >>
    environment:
      NPM_CONFIG_PREFER_OFFLINE: 'true'
  - &size
    resource_class: small
  - &params
    parameters:
      node-version:
        type: string

orbs:
  node: circleci/node@5
  slack: circleci/slack@4

jobs:
  lint:
    <<: *runner
    <<: *size
    <<: *params
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint:prettier
      - run: npm run lint:eslint -- --format junit --output-file reports/eslint/results.xml
  test:
    <<: *runner
    <<: *size
    <<: *params
    steps:
      - checkout
      - run: git submodule sync
      - node/install-packages
      - run: npm test

workflows:
  build:
    jobs:
      - lint:
          node-version: lts
          post-steps:
            - store_test_results:
                path: reports
      - test:
          context: shared-vars
          requires:
            - lint
          matrix:
            parameters:
              node-version:
                - lts
                - current
          post-steps:
            - slack/notify:
                event: fail
                template: basic_fail_1
